export const publicRoutes = [
  "/",
  "/services",
  "/services/software-development",
  "/services/mobile-app-development",
  "/services/ai-llm-automation",
  "/services/design-creative",
  "/services/crm-erp-solutions",
  "/work",
  "/scale",
  "/about",
  "/blog",
  "/contact",
  "/careers",
  "/privacy-policy",
  "/terms-of-use",
  "/cookie-policy",
] as const;
